#!/bin/bash
# 插入测试交易数据

echo "正在插入测试数据..."

# 使用 sqlplus 通过 Docker 连接
cat <<EOF | docker run --rm -i --network host gvenzl/oracle-xe:11-slim sqlplus -s system/helowin@//host.docker.internal:1521/helowin
SET SERVEROUTPUT ON;
INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES ('TEST' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'ACC99999999', 1000.00, SYSTIMESTAMP, 'DEPOSIT', 'MER999999', 'SUCCESS');

INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES ('TEST' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '01', 'ACC88888888', 2000.00, SYSTIMESTAMP, 'TRANSFER', 'MER888888', 'SUCCESS');

INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES ('TEST' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '02', 'ACC77777777', 3000.00, SYSTIMESTAMP, 'PAY', 'MER777777', 'SUCCESS');

COMMIT;
EXIT;
EOF

echo "✅ 测试数据插入完成"
echo "等待 15 秒后检查输出..."
sleep 15

echo "检查最新文件:"
find output/cdc/ -type f -mmin -2 -exec ls -lh {} \;
