#!/bin/bash
# 简化的 Oracle CDC 配置检查脚本
# 使用 Docker 容器中的工具来检查数据库状态

set -e

# 读取环境变量
source .env 2>/dev/null || true

DB_HOST="${DATABASE_HOST:-localhost}"
DB_PORT="${DATABASE_PORT:-1521}"
DB_SID="${DATABASE_SID:-helowin}"
DB_USER="${DATABASE_USERNAME:-system}"
DB_PASSWORD="${DATABASE_PASSWORD:-password}"
DB_SCHEMA="${DATABASE_SCHEMA:-finance_user}"
DB_TABLES="${DATABASE_TABLES:-trans_info}"

echo "=========================================="
echo "Oracle CDC 配置状态检查"
echo "=========================================="
echo "数据库: ${DB_HOST}:${DB_PORT}/${DB_SID}"
echo "用户: ${DB_USER}"
echo "Schema: ${DB_SCHEMA}"
echo "表: ${DB_TABLES}"
echo ""

# 检查是否可以连接到数据库
echo "正在测试数据库连接..."
if nc -z -w 5 localhost ${DB_PORT} 2>/dev/null; then
    echo "✅ 数据库端口 ${DB_PORT} 可访问"
else
    echo "❌ 无法连接到数据库端口 ${DB_PORT}"
    echo "请确保 Oracle 数据库正在运行"
    exit 1
fi

echo ""
echo "=========================================="
echo "Oracle LogMiner CDC 要求"
echo "=========================================="
echo ""
echo "要使用 LogMiner CDC，Oracle 数据库需要满足以下条件："
echo ""
echo "1. 归档日志模式（ARCHIVELOG）"
echo "   检查命令: SELECT LOG_MODE FROM V\$DATABASE;"
echo "   应该返回: ARCHIVELOG"
echo ""
echo "2. 补充日志（Supplemental Logging）"
echo "   启用命令: ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;"
echo "   检查命令: SELECT SUPPLEMENTAL_LOG_DATA_MIN, SUPPLEMENTAL_LOG_DATA_ALL FROM V\$DATABASE;"
echo "   应该返回: YES 或 IMPLICIT"
echo ""
echo "3. 用户权限"
echo "   需要以下权限："
echo "   - SELECT ANY TABLE"
echo "   - EXECUTE_CATALOG_ROLE"
echo "   - SELECT ANY TRANSACTION"
echo "   - LOGMINING (Oracle 12c+)"
echo ""
echo "=========================================="
echo "配置步骤"
echo "=========================================="
echo ""
echo "如果你有 DBA 权限，可以执行以下步骤："
echo ""
echo "步骤 1: 连接到数据库"
echo "  如果数据库在 Docker 容器中："
echo "    docker exec -it <oracle-container> sqlplus / as sysdba"
echo ""
echo "  如果数据库在本地："
echo "    sqlplus / as sysdba"
echo ""
echo "步骤 2: 启用归档日志（如果未启用）"
echo "    SHUTDOWN IMMEDIATE;"
echo "    STARTUP MOUNT;"
echo "    ALTER DATABASE ARCHIVELOG;"
echo "    ALTER DATABASE OPEN;"
echo ""
echo "步骤 3: 启用补充日志"
echo "    ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;"
echo ""
echo "步骤 4: 授予用户权限"
echo "    GRANT SELECT ANY TABLE TO ${DB_USER};"
echo "    GRANT EXECUTE_CATALOG_ROLE TO ${DB_USER};"
echo "    GRANT SELECT ANY TRANSACTION TO ${DB_USER};"
echo "    GRANT LOGMINING TO ${DB_USER};"
echo ""
echo "=========================================="
echo "验证配置"
echo "=========================================="
echo ""
echo "配置完成后，可以运行以下 SQL 验证："
echo ""
echo "-- 检查归档日志"
echo "SELECT LOG_MODE FROM V\$DATABASE;"
echo ""
echo "-- 检查补充日志"
echo "SELECT SUPPLEMENTAL_LOG_DATA_MIN, SUPPLEMENTAL_LOG_DATA_ALL FROM V\$DATABASE;"
echo ""
echo "-- 检查用户权限"
echo "SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE = UPPER('${DB_USER}');"
echo ""
echo "=========================================="
echo "当前可用的 CDC 方式"
echo "=========================================="
echo ""
echo "1. 轮询方式（JdbcCDCApp）- 当前正在使用"
echo "   ✅ 无需特殊配置"
echo "   ✅ 可以立即使用"
echo "   ❌ 只能捕获 INSERT 操作"
echo "   ❌ 延迟较高（${POLL_INTERVAL_SECONDS:-10} 秒）"
echo ""
echo "2. LogMiner 方式（OracleCDCApp）- 需要配置"
echo "   ✅ 实时捕获所有变更（INSERT/UPDATE/DELETE）"
echo "   ✅ 延迟低（秒级）"
echo "   ❌ 需要启用归档日志和补充日志"
echo "   ❌ 需要额外的磁盘空间"
echo ""
echo "=========================================="
echo "下一步"
echo "=========================================="
echo ""
echo "如果你可以配置数据库："
echo "  1. 按照上述步骤配置 Oracle 数据库"
echo "  2. 运行: ./submit-oracle-cdc.sh"
echo ""
echo "如果你无法配置数据库："
echo "  继续使用当前的轮询方式（JdbcCDCApp）"
echo "  当前作业正在运行，可以查看输出："
echo "    ls -la output/cdc/"
echo ""
echo "=========================================="
