-- 创建序列（如果不存在）
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_sequences WHERE sequence_name = 'SEQ_TRANS_ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TRANS_ID START WITH 1000 INCREMENT BY 1';
  END IF;
END;
/

-- 插入测试数据
INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_TYPE, AMOUNT, TRANS_DATE, DESCRIPTION)
VALUES (SEQ_TRANS_ID.NEXTVAL, 'DEPOSIT', 3000.00, SYSDATE, 'Test CDC Insert 3');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_TYPE, AMOUNT, TRANS_DATE, DESCRIPTION)
VALUES (SEQ_TRANS_ID.NEXTVAL, 'WITHDRAWAL', 1500.00, SYSDATE, 'Test CDC Insert 4');

COMMIT;

-- 显示插入的数据
SELECT * FROM (SELECT * FROM FINANCE_USER.TRANS_INFO ORDER BY TRANS_DATE DESC) WHERE ROWNUM <= 5;

EXIT;
