#!/usr/bin/env bash
# 本地单独启动 Flink（单 JM+TM），checkpoint / FileSink 走 OSS
set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RUNTIME_DIR="$SCRIPT_DIR/runtime"
CONF_DIR="$RUNTIME_DIR/conf"
LOG_DIR="$RUNTIME_DIR/logs"
PID_DIR="$RUNTIME_DIR/pids"
PLUGIN_DIR="$RUNTIME_DIR/plugins/oss-fs-hadoop"

# shellcheck disable=SC1091
source "$SCRIPT_DIR/_lib.sh"

yaml_quote() {
    # YAML 双引号转义，避免 SK 中的 $ # : 空格等破坏 fs.oss.*
    local s="${1-}"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    printf '"%s"' "$s"
}

load_env() {
    if [ ! -f "$SCRIPT_DIR/env.sh" ]; then
        echo -e "${RED}缺少 env.sh${NC}"
        echo "  cp $SCRIPT_DIR/env.sh.example $SCRIPT_DIR/env.sh && vim env.sh"
        exit 1
    fi
    # shellcheck disable=SC1091
    source "$SCRIPT_DIR/env.sh"
    echo -e "${GREEN}✓ 已加载 env.sh${NC}"

    : "${FLINK_HOME:?请在 env.sh 设置 FLINK_HOME}"
    normalize_flink_home
    : "${OSS_ENDPOINT:?}"
    : "${OSS_ACCESS_KEY_ID:?}"
    : "${OSS_ACCESS_KEY_SECRET:?}"
    : "${OSS_BUCKET_NAME:?}"
    : "${CHECKPOINT_DIR:?}"
    : "${SAVEPOINT_DIR:?}"
    : "${OUTPUT_PATH:?}"

    REST_PORT="${REST_PORT:-18081}"
    RPC_PORT="${RPC_PORT:-16123}"
    CHECKPOINT_INTERVAL_MS="${CHECKPOINT_INTERVAL_MS:-10000}"
    OSS_PREFIX="${OSS_PREFIX:-localosstest/}"

    if is_windows; then
        echo -e "${YELLOW}⚠ 检测到 Windows/Git Bash：将用 start-cluster.bat（避免 .sh classpath 用 ':' 导致 ClassNotFound）${NC}"
    fi
}

check_prereq() {
    echo -e "${BLUE}>>> 检查环境${NC}"
    local starter
    starter="$(start_cluster_script)"
    if [ ! -f "$starter" ]; then
        echo -e "${RED}✗ FLINK_HOME 无效（找不到启动脚本）: $FLINK_HOME${NC}"
        echo "  期望: bin/start-cluster.bat（Windows）或 bin/start-cluster.sh"
        exit 1
    fi
    if ! ls "$FLINK_HOME"/opt/flink-oss-fs-hadoop-*.jar >/dev/null 2>&1; then
        echo -e "${RED}✗ 未找到 $FLINK_HOME/opt/flink-oss-fs-hadoop-*.jar${NC}"
        echo "  请使用官方完整发行包（含 opt/），不要只用精简目录"
        exit 1
    fi
    if ! command -v java >/dev/null 2>&1; then
        echo -e "${RED}✗ 未找到 java，请安装 JDK 11+ 并配置 PATH/JAVA_HOME${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Flink: $FLINK_HOME${NC}"
    echo -e "${GREEN}✓ start : $starter${NC}"
    echo -e "${GREEN}✓ Java  : $(java -version 2>&1 | head -1)${NC}"
    echo -e "${GREEN}✓ REST : http://localhost:${REST_PORT}${NC}"
    echo -e "${GREEN}✓ CK   : $CHECKPOINT_DIR${NC}"
    echo -e "${GREEN}✓ OUT  : $OUTPUT_PATH${NC}"
}

ensure_oss_plugin() {
    echo -e "${BLUE}>>> 启用 OSS 插件 (flink-oss-fs-hadoop + JAXB)${NC}"
    mkdir -p "$PLUGIN_DIR"
    local oss_jar
    oss_jar="$(ls "$FLINK_HOME"/opt/flink-oss-fs-hadoop-*.jar | head -1)"
    cp -f "$oss_jar" "$PLUGIN_DIR/"

    local maven_base="https://repo1.maven.org/maven2"
    local aliyun_base="https://maven.aliyun.com/repository/public"
    download_jar() {
        local path="$1" name="$2"
        if [ -f "$PLUGIN_DIR/$name" ]; then
            return 0
        fi
        echo "  下载 $name ..."
        curl -fsSL "${aliyun_base}/${path}" -o "$PLUGIN_DIR/$name" \
            || curl -fsSL "${maven_base}/${path}" -o "$PLUGIN_DIR/$name"
    }
    download_jar "javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar" "jaxb-api-2.3.1.jar"
    download_jar "com/sun/xml/bind/jaxb-impl/2.3.1/jaxb-impl-2.3.1.jar" "jaxb-impl-2.3.1.jar"
    download_jar "com/sun/xml/bind/jaxb-core/2.3.0.1/jaxb-core-2.3.0.1.jar" "jaxb-core-2.3.0.1.jar"
    download_jar "javax/activation/activation/1.1.1/activation-1.1.1.jar" "activation-1.1.1.jar"

    install_oss_plugin_link_or_copy "$PLUGIN_DIR"
    echo -e "${GREEN}✓ 插件: $FLINK_HOME/plugins/oss-fs-hadoop${NC}"
}

render_conf() {
    echo -e "${BLUE}>>> 生成独立 FLINK_CONF_DIR${NC}"
    mkdir -p "$CONF_DIR" "$LOG_DIR" "$PID_DIR"

    # 日志配置从发行版拷贝（不覆盖用户全局 conf）
    for f in log4j.properties log4j-console.properties log4j-cli.properties \
             log4j-session.properties logback.xml logback-console.xml logback-session.xml; do
        if [ -f "$FLINK_HOME/conf/$f" ]; then
            cp -f "$FLINK_HOME/conf/$f" "$CONF_DIR/$f"
        fi
    done

    printf 'localhost:%s\n' "$REST_PORT" > "$CONF_DIR/masters"
    printf 'localhost\n' > "$CONF_DIR/workers"

    local ep ak sk upload_dir conf_dir_for_java log_dir_for_java
    # 只用 config.yaml（标准 YAML / SnakeYAML 会去掉引号）。
    # 若同时写 flink-conf.yaml，1.20 会走 legacy 解析器，双引号会变成值的一部分，
    # 导致 fs.oss.accessKeyId 实际为 "AK..." 从而 SignatureDoesNotMatch。
    rm -f "$CONF_DIR/flink-conf.yaml"
    ep="$(yaml_quote "$OSS_ENDPOINT")"
    ak="$(yaml_quote "$OSS_ACCESS_KEY_ID")"
    sk="$(yaml_quote "$OSS_ACCESS_KEY_SECRET")"
    # Windows JVM 需要 C:/...，不能写 Git Bash 的 /c/...
    upload_dir="$(to_flink_path "$RUNTIME_DIR/upload")"
    conf_dir_for_java="$(to_flink_path "$CONF_DIR")"
    log_dir_for_java="$(to_flink_path "$LOG_DIR")"

    cat > "$CONF_DIR/config.yaml" <<EOF
# generated by localosstest/start.sh — do not edit; change env.sh then restart
jobmanager.rpc.address: localhost
jobmanager.rpc.port: ${RPC_PORT}
jobmanager.bind-host: 0.0.0.0
jobmanager.memory.process.size: 1024m

taskmanager.bind-host: 0.0.0.0
taskmanager.host: localhost
taskmanager.memory.process.size: 2048m
taskmanager.numberOfTaskSlots: 4

parallelism.default: 1

execution.checkpointing.interval: ${CHECKPOINT_INTERVAL_MS}
execution.checkpointing.mode: EXACTLY_ONCE
execution.checkpointing.timeout: 300000
state.checkpoints.dir: ${CHECKPOINT_DIR}
state.savepoints.dir: ${SAVEPOINT_DIR}
state.backend.type: hashmap

rest.port: ${REST_PORT}
rest.bind-address: 0.0.0.0
rest.address: localhost
web.upload.dir: ${upload_dir}

fs.oss.endpoint: ${ep}
fs.oss.accessKeyId: ${ak}
fs.oss.accessKeySecret: ${sk}

classloader.resolve-order: parent-first
env.java.opts.all: --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED
EOF

    mkdir -p "$RUNTIME_DIR/upload"
    echo -e "${GREEN}✓ conf: $CONF_DIR/config.yaml${NC}"
    echo "  FLINK_CONF_DIR(java)=${conf_dir_for_java}"
    echo "  web.upload.dir=${upload_dir}"
    # 供 export_flink_env 使用
    FLINK_CONF_DIR_JAVA="$conf_dir_for_java"
    FLINK_LOG_DIR_JAVA="$log_dir_for_java"
    FLINK_PID_DIR_JAVA="$(to_flink_path "$PID_DIR")"
}

export_flink_env() {
    # bash 侧仍可用 Unix 路径访问文件；导出给 Flink/Java 的用 Windows 友好路径
    export FLINK_CONF_DIR="${FLINK_CONF_DIR_JAVA:-$(to_flink_path "$CONF_DIR")}"
    export FLINK_LOG_DIR="${FLINK_LOG_DIR_JAVA:-$(to_flink_path "$LOG_DIR")}"
    export FLINK_PID_DIR="${FLINK_PID_DIR_JAVA:-$(to_flink_path "$PID_DIR")}"
    export FLINK_ENV_JAVA_OPTS="${FLINK_ENV_JAVA_OPTS:-} --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED"
}

start_cluster() {
    if curl -sf "http://127.0.0.1:${REST_PORT}/overview" >/dev/null 2>&1; then
        echo -e "${YELLOW}⚠ Flink 已在运行 (REST ${REST_PORT})${NC}"
        return
    fi
    echo -e "${BLUE}>>> 启动 Flink 集群${NC}"
    export_flink_env
    local starter
    starter="$(start_cluster_script)"
    echo "  exec: $starter"
    echo "  FLINK_CONF_DIR=$FLINK_CONF_DIR"

    # Windows 必须走 .bat；.sh 在 Git Bash 下 classpath 分隔符错误 → ClassNotFoundException
    if [[ "$starter" == *.bat ]]; then
        run_flink_script "$starter" || true
    elif command -v python3 >/dev/null 2>&1 && ! is_windows; then
        # 独立进程组，避免被调用方 shell 退出时误杀 JVM（仅 Unix）
        FLINK_HOME="$FLINK_HOME" python3 - <<PY
import os, subprocess
cmd = [os.environ["FLINK_HOME"] + "/bin/start-cluster.sh"]
subprocess.Popen(cmd, start_new_session=True, env=os.environ.copy())
PY
    else
        nohup "$starter" >/dev/null 2>&1 &
        disown $! 2>/dev/null || true
    fi
    for _ in $(seq 1 60); do
        if curl -sf "http://127.0.0.1:${REST_PORT}/overview" >/dev/null 2>&1; then
            echo -e "${GREEN}✓ Flink 就绪: http://127.0.0.1:${REST_PORT}${NC}"
            return
        fi
        sleep 1
    done
    echo -e "${YELLOW}⚠ 启动超时，看日志:${NC}"
    echo "  $LOG_DIR"
    if is_windows; then
        echo -e "${YELLOW}  若仍是 ClassNotFoundException(org.apache.flink.*):${NC}"
        echo "    1) 确认用的是 start-cluster.bat（本脚本已自动选择）"
        echo "    2) env.sh 中 FLINK_HOME 写成 C:/flink-1.20.x（正斜杠）"
        echo "    3) 或改用 WSL2 跑本脚本（更稳）"
    fi
}

show_status() {
    echo ""
    echo "=========================================="
    echo "  localosstest"
    echo "=========================================="
    if curl -sf "http://localhost:${REST_PORT}/overview" >/dev/null 2>&1; then
        echo -e "  Flink UI: ${GREEN}http://localhost:${REST_PORT}${NC}"
    else
        echo -e "  Flink UI: ${RED}未运行${NC}"
    fi
    echo "  CONF_DIR: $CONF_DIR"
    echo "  CK_DIR  : $CHECKPOINT_DIR"
    echo "  OUT     : $OUTPUT_PATH"
    echo "  提交作业: $SCRIPT_DIR/submit-smoke.sh"
    echo "=========================================="
}

do_build() {
    echo -e "${BLUE}>>> 构建 smoke jar${NC}"
    (cd "$SCRIPT_DIR" && mvn -q -DskipTests package)
    echo -e "${GREEN}✓ $(ls "$SCRIPT_DIR"/target/localosstest-smoke.jar)${NC}"
}

case "${1:-start}" in
    build)
        load_env
        do_build
        ;;
    start)
        load_env
        check_prereq
        ensure_oss_plugin
        render_conf
        start_cluster
        show_status
        ;;
    status)
        load_env
        show_status
        ;;
    conf)
        load_env
        render_conf
        echo "仅生成配置，未启动集群"
        ;;
    -h|--help)
        echo "用法: ./start.sh [start|build|status|conf|--help]"
        ;;
    *)
        echo "未知命令: $1"
        exit 1
        ;;
esac
