-- 创建测试表
CREATE TABLE FINANCE_USER.TEST_CDC (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(100),
  AMOUNT NUMBER(10,2),
  CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 插入测试数据
INSERT INTO FINANCE_USER.TEST_CDC (ID, NAME, AMOUNT) VALUES (1, 'Test 1', 100.00);
INSERT INTO FINANCE_USER.TEST_CDC (ID, NAME, AMOUNT) VALUES (2, 'Test 2', 200.00);
INSERT INTO FINANCE_USER.TEST_CDC (ID, NAME, AMOUNT) VALUES (3, 'Test 3', 300.00);

COMMIT;

SELECT * FROM FINANCE_USER.TEST_CDC;

EXIT;
