-- 创建账户信息表
-- 用于测试多表 CDC 捕获

-- 创建表
CREATE TABLE FINANCE_USER.ACCOUNT_INFO (
    ID NUMBER PRIMARY KEY,
    ACCOUNT_ID VARCHAR2(20) NOT NULL,
    ACCOUNT_NAME VARCHAR2(100),
    ACCOUNT_TYPE VARCHAR2(20),
    BALANCE NUMBER(15,2) DEFAULT 0,
    STATUS VARCHAR2(10) DEFAULT 'ACTIVE',
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_TIME DATE DEFAULT SYSDATE
);

-- 添加注释
COMMENT ON TABLE FINANCE_USER.ACCOUNT_INFO IS '账户信息表';
COMMENT ON COLUMN FINANCE_USER.ACCOUNT_INFO.ID IS '主键ID';
COMMENT ON COLUMN FINANCE_USER.ACCOUNT_INFO.ACCOUNT_ID IS '账户编号';
COMMENT ON COLUMN FINANCE_USER.ACCOUNT_INFO.ACCOUNT_NAME IS '账户名称';
COMMENT ON COLUMN FINANCE_USER.ACCOUNT_INFO.ACCOUNT_TYPE IS '账户类型';
COMMENT ON COLUMN FINANCE_USER.ACCOUNT_INFO.BALANCE IS '账户余额';
COMMENT ON COLUMN FINANCE_USER.ACCOUNT_INFO.STATUS IS '账户状态';
COMMENT ON COLUMN FINANCE_USER.ACCOUNT_INFO.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN FINANCE_USER.ACCOUNT_INFO.UPDATED_TIME IS '更新时间';

-- 启用补充日志（CDC 必需）
ALTER TABLE FINANCE_USER.ACCOUNT_INFO ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- 插入测试数据
INSERT INTO FINANCE_USER.ACCOUNT_INFO (ID, ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE, STATUS)
VALUES (1, 'ACC001', 'John Doe', 'SAVINGS', 10000.00, 'ACTIVE');

INSERT INTO FINANCE_USER.ACCOUNT_INFO (ID, ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE, STATUS)
VALUES (2, 'ACC002', 'Jane Smith', 'CHECKING', 5000.00, 'ACTIVE');

INSERT INTO FINANCE_USER.ACCOUNT_INFO (ID, ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE, STATUS)
VALUES (3, 'ACC003', 'Bob Johnson', 'SAVINGS', 15000.00, 'ACTIVE');

COMMIT;

-- 显示创建结果
SELECT 'Created ACCOUNT_INFO table with ' || COUNT(*) || ' records' AS RESULT 
FROM FINANCE_USER.ACCOUNT_INFO;
