-- 插入测试数据到 TRANS_INFO 表
INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES ('TEST' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'ACC99999999', 1000.00, SYSTIMESTAMP, 'TEST', 'MER999999', 'SUCCESS');

INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES ('TEST' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '01', 'ACC88888888', 2000.00, SYSTIMESTAMP, 'TEST', 'MER888888', 'SUCCESS');

INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES ('TEST' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '02', 'ACC77777777', 3000.00, SYSTIMESTAMP, 'TEST', 'MER777777', 'SUCCESS');

COMMIT;
