-- 测试插入18条记录
-- 用于验证自动提交功能和数据捕获

-- 插入18条测试记录
INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-001', SYSDATE, 100.00, 'PENDING', 'Auto-submit test record 1');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-002', SYSDATE, 200.00, 'PENDING', 'Auto-submit test record 2');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-003', SYSDATE, 300.00, 'PENDING', 'Auto-submit test record 3');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-004', SYSDATE, 400.00, 'PENDING', 'Auto-submit test record 4');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-005', SYSDATE, 500.00, 'PENDING', 'Auto-submit test record 5');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-006', SYSDATE, 600.00, 'PENDING', 'Auto-submit test record 6');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-007', SYSDATE, 700.00, 'PENDING', 'Auto-submit test record 7');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-008', SYSDATE, 800.00, 'PENDING', 'Auto-submit test record 8');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-009', SYSDATE, 900.00, 'PENDING', 'Auto-submit test record 9');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-010', SYSDATE, 1000.00, 'PENDING', 'Auto-submit test record 10');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-011', SYSDATE, 1100.00, 'PENDING', 'Auto-submit test record 11');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-012', SYSDATE, 1200.00, 'PENDING', 'Auto-submit test record 12');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-013', SYSDATE, 1300.00, 'PENDING', 'Auto-submit test record 13');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-014', SYSDATE, 1400.00, 'PENDING', 'Auto-submit test record 14');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-015', SYSDATE, 1500.00, 'PENDING', 'Auto-submit test record 15');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-016', SYSDATE, 1600.00, 'PENDING', 'Auto-submit test record 16');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-017', SYSDATE, 1700.00, 'PENDING', 'Auto-submit test record 17');

INSERT INTO FINANCE_USER.TRANS_INFO (TRANS_ID, TRANS_DATE, AMOUNT, STATUS, DESCRIPTION) 
VALUES ('TEST-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') || '-018', SYSDATE, 1800.00, 'PENDING', 'Auto-submit test record 18');

COMMIT;

-- 显示插入结果
SELECT 'Inserted 18 test records' AS RESULT FROM DUAL;
