INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES (FINANCE_USER.SEQ_TRANS_INFO.NEXTVAL, 'ACC004', 400.00, SYSTIMESTAMP, 'PURCHASE', 'MERCH004', 'SUCCESS');
COMMIT;
SELECT 'Test record inserted successfully' FROM DUAL;
EXIT;
