-- 测试插入数据到 TRANS_INFO 表
-- 用于验证 Flink CDC 是否能捕获新数据并生成 CSV 文件

INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES (SEQ_TRANS_INFO.NEXTVAL, 'TEST_ACC_001', 100.50, SYSTIMESTAMP, 'PURCHASE', 'MERCHANT_001', 'SUCCESS');

INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES (SEQ_TRANS_INFO.NEXTVAL, 'TEST_ACC_002', 200.75, SYSTIMESTAMP, 'TRANSFER', 'MERCHANT_002', 'PENDING');

INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES (SEQ_TRANS_INFO.NEXTVAL, 'TEST_ACC_003', 50.25, SYSTIMESTAMP, 'WITHDRAWAL', 'MERCHANT_003', 'SUCCESS');

COMMIT;

-- 查询最新插入的记录
SELECT * FROM FINANCE_USER.TRANS_INFO WHERE ACCOUNT_ID LIKE 'TEST_ACC_%' ORDER BY ID DESC;
