-- 测试 ACCOUNT_INFO 表的 CDC 捕获
-- 在作业运行时插入新数据

SET SERVEROUTPUT ON
SET FEEDBACK ON

-- 检查表是否存在
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count 
    FROM all_tables 
    WHERE table_name = 'ACCOUNT_INFO' AND owner = 'FINANCE_USER';
    
    IF v_count = 0 THEN
        DBMS_OUTPUT.PUT_LINE('错误: ACCOUNT_INFO 表不存在，需要先创建');
    ELSE
        DBMS_OUTPUT.PUT_LINE('✓ ACCOUNT_INFO 表存在');
    END IF;
END;
/

-- 插入测试数据（作业启动后的新数据）
PROMPT ========== 插入测试数据 ==========

INSERT INTO FINANCE_USER.ACCOUNT_INFO (ID, ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE, STATUS)
VALUES (1001, 'ACC1001', 'Test Account 1', 'SAVINGS', 10000.00, 'ACTIVE');

INSERT INTO FINANCE_USER.ACCOUNT_INFO (ID, ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE, STATUS)
VALUES (1002, 'ACC1002', 'Test Account 2', 'CHECKING', 20000.00, 'ACTIVE');

INSERT INTO FINANCE_USER.ACCOUNT_INFO (ID, ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE, STATUS)
VALUES (1003, 'ACC1003', 'Test Account 3', 'SAVINGS', 30000.00, 'ACTIVE');

COMMIT;

PROMPT ========== 插入完成 ==========
SELECT COUNT(*) as total_rows FROM FINANCE_USER.ACCOUNT_INFO;

-- 等待 5 秒
EXEC DBMS_LOCK.SLEEP(5);

-- 更新测试数据
PROMPT ========== 更新测试数据 ==========

UPDATE FINANCE_USER.ACCOUNT_INFO 
SET BALANCE = BALANCE + 1000, STATUS = 'UPDATED'
WHERE ID = 1001;

UPDATE FINANCE_USER.ACCOUNT_INFO 
SET ACCOUNT_NAME = 'Updated Account 2'
WHERE ID = 1002;

COMMIT;

PROMPT ========== 更新完成 ==========
PROMPT 请等待 10-15 秒，然后检查输出目录是否生成了 ACCOUNT_INFO 的 CSV 文件

EXIT;
