INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES (999001, 'ACC005', 500.00, SYSTIMESTAMP, 'TRANSFER', 'MERCH005', 'SUCCESS');
COMMIT;
SELECT 'CDC test record inserted with ID 999001' FROM DUAL;
EXIT;
