INSERT INTO FINANCE_USER.TRANS_INFO (ID, ACCOUNT_ID, AMOUNT, TRANS_TIME, TRANS_TYPE, MERCHANT_ID, STATUS)
VALUES (999999, 'ACC_TEST', 888.88, SYSTIMESTAMP, 'TEST_CDC', 'MERCH_TEST', 'PENDING');
COMMIT;
SELECT 'CDC test: Record 999999 inserted at ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
EXIT;
