UPDATE FINANCE_USER.TRANS_INFO 
SET AMOUNT = 999.99, STATUS = 'COMPLETED', TRANS_TYPE = 'CDC_TEST_UPDATE'
WHERE ID = 999999;
COMMIT;
SELECT 'CDC test: Record 999999 updated at ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') || ', rows affected: ' || SQL%ROWCOUNT FROM DUAL;
EXIT;
